apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-ngfw-config
  namespace: kube-system
data:
  PAN_SERVICE_NAME: "{{ .Values.firewall.serviceName }}" # should match the pan-mgmt's Service name
  FAILOVER_MODE: "{{ .Values.firewall.failoverMode }}"     # licensing failure behavior
  DP_RINGBUFFER: "60000"        # buffer count for memory/performance control
  #IPSEC_NAT_PORT_RANGE: "4500-4500"    # port range to avoid stale connections
